# Generated by Django 3.0.6 on 2020-05-30 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date_of_rent', models.DateTimeField(default=datetime.datetime(2020, 5, 30, 15, 55, 16, 342755), verbose_name='Date of rent')),
                ('date_of_return', models.DateTimeField(verbose_name='Date of return')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsy.Employee')),
                ('tools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsy.Tools')),
            ],
        ),
    ]
